// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIcG0B1sUaePNYsloeFnvc20-DXD85-aM',
    appId: '1:453171614776:web:6f0a9c58b4f968dc8c02cd',
    messagingSenderId: '453171614776',
    projectId: 'vita-86079',
    authDomain: 'vita-86079.firebaseapp.com',
    storageBucket: 'vita-86079.firebasestorage.app',
    measurementId: 'G-FF5KQML71K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrXT-G7LaVd6j-2gKm3HM0GgjiqiQUpVo',
    appId: '1:453171614776:android:f5aeeb551eae19f28c02cd',
    messagingSenderId: '453171614776',
    projectId: 'vita-86079',
    storageBucket: 'vita-86079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfbmBOMuoIdGMSPg0pcxcNgvCTbrRsmwA',
    appId: '1:453171614776:ios:107e356f1a97febb8c02cd',
    messagingSenderId: '453171614776',
    projectId: 'vita-86079',
    storageBucket: 'vita-86079.firebasestorage.app',
    iosBundleId: 'com.example.vita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfbmBOMuoIdGMSPg0pcxcNgvCTbrRsmwA',
    appId: '1:453171614776:ios:107e356f1a97febb8c02cd',
    messagingSenderId: '453171614776',
    projectId: 'vita-86079',
    storageBucket: 'vita-86079.firebasestorage.app',
    iosBundleId: 'com.example.vita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIcG0B1sUaePNYsloeFnvc20-DXD85-aM',
    appId: '1:453171614776:web:b349e9986ecefec98c02cd',
    messagingSenderId: '453171614776',
    projectId: 'vita-86079',
    authDomain: 'vita-86079.firebaseapp.com',
    storageBucket: 'vita-86079.firebasestorage.app',
    measurementId: 'G-5PFLXV1T5X',
  );

}